### ISSUE TITLE
dont start

### ISSUE THREAD

**Issue by jokerschwab** [EdwynZN/amiibo_network#14]
The App Stuck at the logo since Update to Android 12. Please Help me

King regards

**Comment by EdwynZN** [comment]
Are you using the last update of November 8th ?

**Comment by EdwynZN** [comment]
I will check that, in the meantime if you can give a review in Google Play (1 star is ok) so I can see the data related to the app you're using

**Comment by EdwynZN** [comment]
I checked but It's weird that I cannot see the metadata of the App you're using in Google Play. Still sill check on Android 12 related problems

**Comment by jokerschwab** [comment]
1.4.1d solved the problem
