### ISSUE TITLE
Handshake error - Certificate expired

### ISSUE THREAD

**Issue by lennaick** [EdwynZN/amiibo_network#17]
When I double tab on any figurine or card I've got the following error

`HandshakeException: Handshake error in client (OS Error: CERTIFICATE VERIFY FAILED: certificate has expired(handshake.cc:359)) `

My phone is an old Samsung Galaxy A5 (2017) with android 7 (Nougat)

**Comment by EdwynZN** [comment]
https://github.com/flutterchina/dio/issues/1028#issue-784934077

It seems a problem with an http connection when fetching games compatibility with the amiibo, I'll investigate further

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/22

It seems related to local zone of the device sometimes, but it's something way off me
