### ISSUE TITLE
Amiibo functions

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#18]
Hey, i Love your App ,but i have a question, where did you get These Infos and are these info as a Text File in the folders on github?  i hope you understand what i mean 😅

**Comment by EdwynZN** [comment]
What do you mean by info? The relationship of the aminos with their release dates, games and all?

**Comment by Ericzion1999** [comment]
No , i mean this :![Screenshot_2022-02-12-00-58-51-167_com.dartz.amiibo_network.jpg](https://user-images.githubusercontent.com/82835573/153696012-f4539df0-a867-433c-a716-45f320de47dd.jpg)

**Comment by EdwynZN** [comment]
I use AmiiboApi to fetch games and usage data

**Comment by Ericzion1999** [comment]
Ah okay thank you
