### ISSUE TITLE
Official release day Monster Hunter sunbreak amiibo

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#19]
![IMG_20220424_015607](https://user-images.githubusercontent.com/82835573/164950399-30b25c1d-ffa6-49e8-9232-a36e0ac94732.jpg)

**Comment by EdwynZN** [comment]
Thank you, I'll try to update it this week

**Comment by Ericzion1999** [comment]
you probably already know it but min min release day is the 29th of this month😅

**Comment by EdwynZN** [comment]
Not at all 🙃, I have been very busy and I don't want to forget this project but I haven't found a time for myself to keep on it.

Thank you for your support and I will continue to upgrade it as soon as I have the time

**Comment by Ericzion1999** [comment]
take your time, I just wanted you to know that the new one is coming out or that the release date is now set.  Your app is the best I've seen so far, I recommend it to anyone looking for an app like this 🔥

**Comment by EdwynZN** [comment]
#20

**Comment by Ericzion1999** [comment]
30th June is also the Release Date for Europe

**Comment by EdwynZN** [comment]
I see that, I'll update it with a fix of showing games with those amiibos not loading corretly

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/22
