### ISSUE TITLE
amiibo update

### ISSUE THREAD

**Issue by jokerschwab** [EdwynZN/amiibo_network#21]
First. Nice Job with the App. Best App i have Seen for amiibo.   Pleased Update the 3 new splaroon amiibo

Greet jokerschwab

**Comment by Ericzion1999** [comment]
I'm joining Jokerschwab and Steve and Alex are coming out on September 9th.
Take the time you need.

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/22

**Comment by EdwynZN** [comment]
Release is in progress in the play store
