### ISSUE TITLE
Min min amiibo Shows ,,To be announced,,

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#24]
I have the Latest Apk installed 
![Screenshot_2022-08-14-19-03-12-403_com dartz amiibo_network](https://user-images.githubusercontent.com/82835573/184547432-cdbc374f-677b-4ddc-8fd7-821e33bd8eef.jpg)

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/25

Fixing it right now

**Comment by Ericzion1999** [comment]
It is fixed now
