### ISSUE TITLE
No exporta lista de amiibos

### ISSUE THREAD

**Issue by JJBEJARANOCA** [EdwynZN/amiibo_network#26]
No exporta la lista, valide en diferentes carpetas al igual que los permisos, pero no sé evidencia el archivo.[Prueba](https://youtu.be/AOy077ma2HU)

**Comment by EdwynZN** [comment]
Qué version de Android es? 12?

**Comment by JJBEJARANOCA** [comment]
Correcto, v12.



Jonathan Bejarano
________________________________

**Comment by EdwynZN** [comment]
#28 

La versión con el fix para Android 12 debería salir esta semana, al igual esta el [release](https://github.com/EdwynZN/amiibo_network/releases/tag/1.5.0%2B51)
