### ISSUE TITLE
Sugerencia: permitir elegir entre figura y tarjeta

### ISSUE THREAD

**Issue by JJBEJARANOCA** [EdwynZN/amiibo_network#27]
Que permita ver figuras, tarjeta o las dos, por defecto, sin tener que seleccionar la opción. En mi caso no tengo intención de coleccionar las tarjetas y al estar por defecto al abrir la aplicación, siempre debo seleccionar figuras.

**Comment by EdwynZN** [comment]
Puedes crear tu propia lista personalizada y la App detectara que existe e iniciara siempre en esa en vez de Todos https://github.com/EdwynZN/amiibo_network/pull/30
