### ISSUE TITLE
Consider using a less aggressive color theme for onboarding

### ISSUE THREAD

**Issue by AndreasWebdev** [EdwynZN/amiibo_network#3]
Hey there, great app!

Maybe consider using a less aggressive color theme when first starting the app, I myself was quite confused by the bright (and after a few seconds annoying) red. I've checked my thoughts with a small QA group that is helping me with my own apps and they agreed that the bright red might put users off (if they can't find the settings). One tester told me it was "as if the app would scream at me".

Greetings!

**Comment by EdwynZN** [comment]
Thank you for your feedback, as you said after making the themes and changes I noticed that I used too much color in the background, and I'm still trying to figure out a more minimalist theme for light mode with some kind of white color and low saturation colors for the background.

![Nexus5X_home](https://user-images.githubusercontent.com/16828084/73904108-9dd0f980-4860-11ea-86a2-92e5b74a7d19.png)
