### ISSUE TITLE
Custom section

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#32]
i think i'm stupid but how exactly do i use the custom section?

**Comment by EdwynZN** [comment]
yeah i think I didn't make a great UX showing off how to use the custom section, you have to long tap (> 1s) the custom section tile or when you're in and is empty you can tap on the empty text "Nothing to see here ... yet"


<img src=https://user-images.githubusercontent.com/16828084/196327757-cc8fe6e3-d2e1-4ddd-bbcd-7d87f0e45884.png width="30%" height="30%" /> <img src=https://user-images.githubusercontent.com/16828084/196327755-c2e978a3-9bf5-48c0-9e3b-77581e5f84c0.png width="30%" height="30%" />
