### ISSUE TITLE
I don't know if you noticed, but a Mario gold Power Up Band was released on March 18th, 2023 in the super Nintendo World Park Japan

### ISSUE THREAD

**Issue by Brickleberry19** [EdwynZN/amiibo_network#44]
https://topics.nintendo.co.jp/article/55278af4-c190-44f3-ad21-18699f9c749d?utm_source=twitter&utm_medium=social&utm_content=20230315&utm_campaign=topics

![icon_00000003-0430FF02](https://user-images.githubusercontent.com/115247704/227048193-b7539ac5-4eb3-47d8-b83a-ee20415acf60.png)

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/45
