### ISSUE TITLE
Release Date for Pyra and mythra+ 2 new amiibo 

### ISSUE THREAD

**Issue by Brickleberry19** [EdwynZN/amiibo_network#47]
Pyra and mythra have now a Official release Date 21.07.2023 + 2 more characters from Xenoblade get an amiibo

https://twitter.com/NintendoAmerica/status/1648498494133641217?t=2gidG2ATKMAC1Gsb57rQZA&s=19

https://twitter.com/NintendoAmerica/status/1648500990788915200?t=8_Dn0BV8jxmEATY-g_3eTg&s=19

**Comment by EdwynZN** [comment]
Solved in https://github.com/EdwynZN/amiibo_network/pull/48 (waiting approve from PlayStore)
