### ISSUE TITLE
Feature suggestion: Category filter/quick switcher, lock toggle

### ISSUE THREAD

**Issue by jmleetw** [EdwynZN/amiibo_network#5]
Hello, I just found your app one Google Play, and it's really a hidden gem! It has almost all features I wanted, also neat and tidy. Good job!

Here are some feedbacks for Amiibo Network:

A filter to include/exclude specified categories. For example I don't collect Animal Crossing cards, then I can hide the whole Cards section. Or I just want to collect the Super Smash Bros. and Super Mario Bros. series, then I can exclude all other categories from the Figures section.

And I think it takes too many taps to switch between categories. I tried the search features but it's a bit not intuitive. Maybe a quick switcher could be integrated with category filter. 

Also a lock/unlock toggle would be useful for preventing accidental taps. I accidentally tapped and removed a selection two times when scrolling in the app.

Thank you for the great app!

**Comment by EdwynZN** [comment]
Hello @jmleetw, thank you for all your feedback.

A filter like a white/blacklist to show specified categories is a great idea, and I understand that changing between categories takes a bit more with opening the drawer and then selecting the category, I need to think a way to keep both so people who wants to see everything can while the other who wants to see specific can choose it that way,

I wanted to improve the search functionality with the buttons to search by game, series or name, but if its not intuitive I would make some changes as well, what do you mean exactly by a quick switcher with the category filter?

Last lock it's a simple but yet important feature that I didn't think about. I could add the lock/unlock button to the search bar like this and save the preference of the user to prevent taps when opening the app

![Screenshot_1589140374](https://user-images.githubusercontent.com/16828084/81509120-1a46fe80-92ce-11ea-945e-7198cfa66c57.png)
![Screenshot_1589140372](https://user-images.githubusercontent.com/16828084/81509122-1b782b80-92ce-11ea-9916-863c6068f3fc.png)
