### ISSUE TITLE
New Zelda and Ganondorf amiibo announced for totk (Winter 2023)

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#51]
![imgZelda_sp.png](https://github.com/EdwynZN/amiibo_network/assets/82835573/3fc24c4f-caf4-41bf-a9aa-c54f339bc646)

![imgGanondorf_sp.png](https://github.com/EdwynZN/amiibo_network/assets/82835573/f00207f4-7488-4397-8755-44c0740984a6)

**Comment by EdwynZN** [comment]
[Published APK](https://github.com/EdwynZN/amiibo_network/releases/tag/2.1.61%2B70)

The version will be in store shortly
