### ISSUE TITLE
3 new amiibo are announced for Splatoon 

### ISSUE THREAD

**Issue by Brickleberry19** [EdwynZN/amiibo_network#52]
https://twitter.com/NintendoAmerica/status/1692160612556496904
![shiver](https://github.com/EdwynZN/amiibo_network/assets/115247704/a310a7e4-dec6-44cc-9633-a11f82cb961f)
![Frye](https://github.com/EdwynZN/amiibo_network/assets/115247704/c46fafaa-5577-4fa0-b2b8-a1ba534bcf43)
![Big Man](https://github.com/EdwynZN/amiibo_network/assets/115247704/7944ab74-cc63-4730-a417-0ac3de8900e9)

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/53

**Comment by EdwynZN** [comment]
The app is in review and will be published later this weekend
