### ISSUE TITLE
Amiibo news

### ISSUE THREAD

**Issue by Brickleberry19** [EdwynZN/amiibo_network#56]
Ganondorf and Zelda amiibo 3 November
Noah and Mio amiibo 19 Januar
Sora amiibo official in Progress

![800d16c9ae5004dfe68561c8dd9b5ec0f6eb58ee2464c4a1174da9135577c38a1e02839fbb5605bab2f93188dffb411424d2ea34d3bcd4d83c116d1c7be98be3-removebg-preview](https://github.com/EdwynZN/amiibo_network/assets/115247704/8f4b88a5-50c3-4c08-a806-3ab6d23522b0)
![e1a4fdb7b19a059e0181ea53f22015eeed6ec0ed66820533e9761feef238abf0660b47b39bd1acb1c493020b302e4bc9eb1eb36d3518f7dbd121128ee9194430-removebg-preview](https://github.com/EdwynZN/amiibo_network/assets/115247704/f8733389-7688-4143-8bb0-2b0a06c54417)
![34716450018deb9679f019ca2812e3d4080abec615424545ea990ec0118cb875649b2dbd6b4c9a6d593974037b316480d14f019f5fb0d438c8632c54c20eab9f-removebg-preview](https://github.com/EdwynZN/amiibo_network/assets/115247704/9fbd734e-82c5-4032-a778-8cf47281e8fd)

**Comment by EdwynZN** [comment]
Closed: #57
