### ISSUE TITLE
Export Amiibo Functionality Not Working 

### ISSUE THREAD

**Issue by morochaamorocha** [EdwynZN/amiibo_network#59]
The export library functionality doesn't seem to be working. My device is running android 14. App version is 2.1.7.

**Comment by EdwynZN** [comment]
I understand there is a bug in that feautre after Android 12 (its saved but is not shown in any folder because they cahnge the way of the folders). For now try using Xplore File manager and check if there is a folder inside Android > data > amiibo_network with those files

**Comment by EdwynZN** [comment]
#61 working on it
