### ISSUE TITLE
Donkey Kong and Diddy Kong Power Up Bands announced for spring 2024

### ISSUE THREAD

**Issue by Brickleberry19** [EdwynZN/amiibo_network#62]
https://twitter.com/UniNewsToday/status/1731847097152938005?t=3zlTpTYGtavVCX-TTMGD0A&s=19

**Comment by Brickleberry19** [comment]
Here are Images ,Hope they are good enough ![10. Diddy Kong back power up band.png](https://github.com/EdwynZN/amiibo_network/assets/115247704/3a9d3ef8-ffa0-458e-aa16-19f8186901e2)

![9. Donkey Kong back power up band.png](https://github.com/EdwynZN/amiibo_network/assets/115247704/b8acff71-53ae-4d8d-91df-1dcc205332bc)

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/65
