### ISSUE TITLE
Sanio amiibo cards.

### ISSUE THREAD

**Issue by OngoingTalent13** [EdwynZN/amiibo_network#64]
The US release date says March 26th 2016 but they did not release in the US until March 26th 2021.

**Comment by Brickleberry19** [comment]
The official Nintendo usa Website says December 2, 2016

https://www.nintendo.com/us/amiibo/detail/animal-crossing-sanrio-collaboration-pack-amiibo-animal-crossing-series/

**Comment by EdwynZN** [comment]
https://github.com/EdwynZN/amiibo_network/pull/65
