### ISSUE TITLE
Re-enable Cards tab

### ISSUE THREAD

**Issue by cesardka** [EdwynZN/amiibo_network#68]
Hi there!

Is there an update on what happened to the Cards tab? I assume the data for my local collection is there, but it seems the button and all options related to cards were removed recently, but I see no mention of it in the Releases

Thanks for this awesome piece of work!

**Comment by EdwynZN** [comment]
Hello, as far as I know there hasn't been an update nor a bug related to that feature, but I'll investigate. For now, can you check this setting to be sure you didn't hide cards by mistake:

![imagen](https://github.com/EdwynZN/amiibo_network/assets/16828084/85b4d3e9-1dc4-491e-b28e-20f1e0735318)

This is the settings where tapping the pencil (top right, between lock and AZ), make sure both cards and figures are checked. This feature was by a request of people that only want to collect one type and didn't want to see the other
