### ISSUE TITLE
Power up Bands & Zelda and loftwing

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#7]
Hy ,
I wanted to ask if these amiibo's will still appear in the app or Not .

With best regards

**Comment by EdwynZN** [comment]
Hello

I'm aware of the new Zelda amiibo and monster hunter amiibos and I plan to add them at the end of the month

I am not sure about the power up bands, I understand they use NFC but can they be used as amiibos or have some functions in any game?

I'll look up on that and decide if add them as well

**Comment by Ericzion1999** [comment]
the power up bands are normal amiibo's, I know that because I have all 6

**Comment by EdwynZN** [comment]
Thank you for the information, I'll add them with the rest later this month

**Comment by EdwynZN** [comment]
Version 1.4.0 will be published in Play Store later this week (waiting Google review)
-     Added Super Smash Bros. serie Min-Min
-     Added Metroid Dread series Samus and E.M.M.I.
-     Added amiibo Zelda and Loftwing
-     Added amiibo bands of Super Nintendo World
-     Added Monster Hunter Stories series Tsukino, Razewing Ratha and Ena
-     Amiibo details screen updated to show a list of compatible games
-     Stat buttons moved from drawer to home screen
