### ISSUE TITLE
New amiibo announced.

### ISSUE THREAD

**Issue by OngoingTalent13** [EdwynZN/amiibo_network#79]
New Spaltoon amiibo have been announced. Being new versions of Callie, Marie, Pearl, and Marina.

**Comment by Brickleberry19** [comment]
Images without the Background 

![Callie amiibo [alternative].png](https://github.com/user-attachments/assets/f3423eca-e589-4151-9698-40b3a1429829)

![Marina amiibo [alternative].png](https://github.com/user-attachments/assets/eb459d25-531f-4861-baf1-a20e9ae6f2b0)

![Marie amiibo [alternative].png](https://github.com/user-attachments/assets/ede3e3c2-2156-48bf-8de0-64a029ffa06f)

![Pearl amiibo [alternative].png](https://github.com/user-attachments/assets/3c25707e-84d3-49c6-bbe6-35f72cc905ef)

**Comment by Brickleberry19** [comment]
The Official names:
Callie (Alterna)
Marie (Alterna)

Pearl (Side Order)
Marina (Side Order)

**Comment by EdwynZN** [comment]
Will be updated during the weekend

https://github.com/EdwynZN/amiibo_network/pull/80

**Comment by Brickleberry19** [comment]
Thanks for the Update ,but there is a small issue, In the original, in brackets it says Side Order and not alterna for Pearl and Marina![Screenshot_2024-07-21-22-46-45-757-edit_com.twitter.android.jpg](https://github.com/user-attachments/assets/b357a244-8cf4-4566-90d0-e8233d7a7410)

![Screenshot_2024-07-21-22-47-02-940-edit_com.twitter.android.jpg](https://github.com/user-attachments/assets/e4454cef-3674-4a8f-b512-ddc0d44347d5)
