### ISSUE TITLE
Mario, Luigi, Peach, Daisy, Toad, and Yoshi Power-Up Bands

### ISSUE THREAD

**Issue by OngoingTalent13** [EdwynZN/amiibo_network#86]
They released in North America when Super Nintendo Land Hollywood opened on February 23rd, 2023.

**Comment by EdwynZN** [comment]
You mean the release date of the bands in NA?

**Comment by OngoingTalent13** [comment]
Yes

**Comment by EdwynZN** [comment]
#87
