### ISSUE TITLE
Android 15

### ISSUE THREAD

**Issue by jokerschwab** [EdwynZN/amiibo_network#88]
Xiaomi 13T pro Till Update hyper core 2.0.9. Android 15 start the App with a White Screen. I have the App new installed. Problem again. Please fix the App.

King regards jokerschwab

**Comment by EdwynZN** [comment]
#89 I'll release an update to compile against Android 15

**Comment by EdwynZN** [comment]
@jokerschwab can you check with the last update if everything works as intended?

**Comment by jokerschwab** [comment]
I have installed 2.2.23 from 14.12.2024 the issue is the Same. White Screen on start.

**Comment by EdwynZN** [comment]
New release just dropped

**Comment by jokerschwab** [comment]
Sorry 2.2.24 the Same issue. White Screen

**Comment by jokerschwab** [comment]
Version 3.0 solved the Problem. Thanks a lot. Merry Christmas
