### ISSUE TITLE
Yu-Gi-Oh amiibos 

### ISSUE THREAD

**Issue by Ericzion1999** [EdwynZN/amiibo_network#9]
There we're Yu-Gi-Oh amiibos , do you add Them in the Future?

With best regards

**Comment by EdwynZN** [comment]
I'm unaware of these YugiOh Amiibo cards, are they oficial?

**Comment by Ericzion1999** [comment]
Yes , and i have the informations and Images 

https://drive.google.com/folderview?id=1Kha_EsID95dYc5MpvCdoermkkEcvSWyl

**Comment by EdwynZN** [comment]
Thanks for the info, I will make an update of this, probably next weekend

**Comment by EdwynZN** [comment]
New Update is up with YuGiOh amiibo cards with japan release date
